version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_install:
      - make base
      - poetry run invoke docs.install docs.build --no-watch

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
