name: Report a bug
description: If you came across something unexpected, let us know here!
labels: [bug, pending]

body:
  - type: markdown
    attributes:
      value: Thank you for contributing to pydantic! ✊

  # - type: checkboxes
  #   id: checks
  #   attributes:
  #     label: Initial Checks
  #     description: Just making sure you're really using Pydantic V2
  #     options:
  #       - label: I confirm that I'm using Pydantic V2
  #         required: true

  - type: textarea
    id: observed-behaviour
    attributes:
      label: Observed behaviour
      description: |
        Please describe the unexpected behaviour that you observed.

        Make sure to provide as much information as possible, so that we can investigate as thoroughly as we can!
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: |
        Please describe the behaviour that you expected to see.

        If appropriate, provide any links to official Feud documentation that indicate this is the behaviour that is expected.
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Code to reproduce
      description: >
        Please provide a snippet of code that shows how to reproduce the bug, 
        making sure that it is [minimal and reproducible](https://stackoverflow.com/help/minimal-reproducible-example).

      placeholder: |
        """To reproduce my bug, run the following script with:

        python command.py --bug
        """

        # command.py

        import feud

        def command(*, bug: bool = False):
            """Command that demonstrates the bug."""
            if bug:
                raise ValueError("Woops, this is buggy!")

        if __name__ == "__main__":
            feud.run(command)
      render: Python

  - type: textarea
    id: version
    attributes:
      label: Version details
      description: |
        To help us get to the root of the problem as fast as possible, 
        please run the following command to display version information about:

        - Python
        - Feud
        - Operating system

        ```bash
        python -c "import feud; print(feud.version.version_info())"
        ```

      render: Text
    validations:
      required: true
