version: "2.1"

orbs:
  python: circleci/python@2.1.1

executors:
  python:
    name: python/default
    tag: <<parameters.version>>
    working_directory: /tmp

jobs:
  linting:
    parameters:
      version:
        type: string
    executor: python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          args: --only base
      - run:
          name: Linting
          command: |
            poetry run tox -e lint
  tests:
    parameters:
      version:
        type: string
    executor: python
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          args: --only base
      - run:
          name: Docstring tests
          command: |
            poetry run tox -e tests.doctest
      - run:
          name: Unit tests
          command: |
            poetry run -- tox -e tests.unit -- --cov
      - run:
          name: Generate coverage report
          command: |
            mkdir -p coverage/<<parameters.version>>
            cp coverage.xml coverage/<<parameters.version>>
            cat coverage/<<parameters.version>>

workflows:
  checks:
    jobs:
      - linting:
      - tests:
          matrix:
            parameters:
              version: ["3.11", "3.12"]
