version: "2.1"

orbs:
  python: circleci/python@2.1.1

jobs:
  python:
    parameters:
      version:
        type: string
    executor:
      name: python/default
      tag: <<parameters.version>>
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          args: --only base
      - run:
          name: Linting
          command: |
            poetry run tox -e lint
      - run:
          name: Docstring tests
          command: |
            poetry run tox -e tests.doctest
      - run:
          name: Unit tests
          command: |
            poetry run tox -e tests.unit

workflows:
  tests:
    jobs:
      - python:
          matrix:
            parameters:
              version: ["3.11", "3.12"]
