name: Auto-merge master into dev

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  auto-merge:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge master back to dev
        run: |
          git fetch --unshallow
          git checkout dev
          git pull
          git merge --no-ff master -m "chore(git): auto-merge master -> dev"
          git push
