name: Create GitHub release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build and release on GitHub
        uses: "marvinpinto/action-automatic-releases@1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true # change this back once tested
