name: Create release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  create-pull-request:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.7.1
      - name: Install base dependencies
        run: poetry install --sync --only base
      - name: Bump version and changelog
        run: |
          entry="$(poetry run invoke release.install release.build -- -v ${{ github.event.inputs.version }})"
          echo "entry<<EOF"$'\n'"$entry"$'\n'EOF >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
