name: Create release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.7.1
      - name: Install base dependencies
        run: poetry install --sync --only base
      - name: Bump version and changelog
        run: poetry run invoke release.install release.build -- -v ${{ github.event.inputs.version }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "release: v${{ github.event.inputs.version }}"
          title: "release: v${{ github.event.inputs.version }}"
          body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          branch: release/${{ github.event.inputs.version }}
