name: Semantic Pull Request Titles

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate pull request title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          types: |
            chore
            feat
            fix
            misc
            refactor
            release
          scopes: |
            build
            ci
            deps
            docs
            git
            pkg
            tests
            #\d+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
